# Schema for the configuration files of the Commerce TouchNet uPay module.
commerce_touchnet_upay.settings:
  type: config_object
  label: 'Commerce TouchNet uPay settings'
  mapping:
    merchant_id:
      type: string
      label: 'Your Merchant ID with uPay Proxy'
    merchant_store_id:
      type: string
      label: 'Your Merchant Store ID with uPay Proxy'
