# Schema for the configuration files of the Commerce TouchNet uPay module.
commerce_touchnet_upay.settings:
  type: config_object
  label: 'UBC Commerce TouchNet uPay settings'
  mapping:
    base_uri:
      type: string
      label: 'The URI for the uPay Proxy API'
    merchant_id:
      type: string
      label: 'Your Merchant ID with uPay Proxy'
    merchant_store_id:
      type: string
      label: 'Your Merchant Store ID with uPay Proxy'
    merchant_proxy_key:
      type: string
      label: 'Your Merchant secret key'
    merchant_update_secret:
      type: string
      label: 'Your shared secret to validate the request sender'
